name: Run defined suite of tests

on:
  workflow_dispatch:
    inputs:
      suite:
        type: choice
        description: Which suite to execute
        options:
          - daily
          - e2e

permissions:
  actions: write
  contents: write
  pages: write

jobs:
  executeTests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print Java version (pre-installed in Github Actions Runner)
        run: java --version
      - name: Print mvn version (pre-installed in Github Actions Runner)
        run: mvn --version
      - name: Print Google Chrome version (pre-installed in Github Actions Runner)
        run: |
          google-chrome --version
          google-chrome-stable --version
      - name: Run tests
        env:
          DEFAULT_USER: ${{ secrets.DEFAULT_USER }}
          DEFAULT_USER_PASSWORD: ${{ secrets.DEFAULT_USER_PASSWORD }}
          SERVICE_BUS_USER: ${{ secrets.SERVICE_BUS_USER_NAME }}
          SERVICE_BUS_USER_PASSWORD: ${{ secrets.SERVICE_BUS_USER_PASSWORD }}
          DMD_HIBERNATE_PASSWORD: ${{ secrets.DMD_HIBERNATE_PASSWORD }}
          GCDM_HIBERNATE_PASSWORD: ${{ secrets.GCDM_HIBERNATE_PASSWORD }}
          S3_USER: ${{ secrets.S3_USER_NAME }}
          S3_SECRET: ${{ secrets.S3_SECRET_KEY }}
        run: |
          mvn clean test -fn -Dsuite=${{ github.event.inputs.suite }} -Denv=staging -Dheadless=true -Dpersistence_unit=remote
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
         ref: gh-pages
         path: gh-pages
      - name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
