name: Run Dummy tests

on:
  workflow_dispatch:

permissions: write-all
jobs:
  executeTests:
    runs-on: self-hosted
    steps:
      - name: Camunda restart
        run: curl https://oysmfpy2fookwr2tkflfaiwbha0ioqed.lambda-url.us-west-2.on.aws/
      - name: FIX perms
        run: sudo chown ubuntu:ubuntu -R /home/ubuntu
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        id: tests
        env:
          DEFAULT_USER: ${{ secrets.DEFAULT_USER }}
          DEFAULT_USER_PASSWORD: ${{ secrets.DEFAULT_USER_PASSWORD }}
          SERVICE_BUS_USER: ${{ secrets.SERVICE_BUS_USER_NAME }}
          SERVICE_BUS_USER_PASSWORD: ${{ secrets.SERVICE_BUS_USER_PASSWORD }}
          DMD_HIBERNATE_PASSWORD: ${{ secrets.DMD_HIBERNATE_PASSWORD }}
          GCDM_HIBERNATE_PASSWORD: ${{ secrets.GCDM_HIBERNATE_PASSWORD }}
          S3_USER: ${{ secrets.S3_USER_NAME }}
          S3_SECRET: ${{ secrets.S3_SECRET_KEY }}
        run: |
          mvn clean test -fn -Dsuite=dummy -Denv=staging -Dheadless=true -Dpersistence_unit=remote

      - name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: |
                allure-report
